name = "waarisniels"
main = "./dist/_worker.js"
compatibility_date = "2025-08-27"
compatibility_flags = ["nodejs_compat"]

# This tells the Worker where to find your static assets (CSS, JS, images)
[site]
bucket = "./dist"

# This tells Wrangler how to build your project
[build]
command = "npm run build"

[[kv_namespaces]]
binding = "bibbibib"
id = "adadbaa37ca743d5a6c3e3b2d311fb3c"
preview_id = "adadbaa37ca743d5a6c3e3b2d311fb3c"

[[kv_namespaces]]
binding = "SESSION"
id = "adadbaa37ca743d5a6c3e3b2d311fb3c"
preview_id = "adadbaa37ca743d5a6c3e3b2d311fb3c"