name = "waarisniels"
pages_build_output_dir = "dist" # <-- DEZE REGEL IS CRUCIAAL

compatibility_date = "2025-08-28"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "bibbibib"
id = "adadbaa37ca743d5a6c3e3b2d311fb3c"
preview_id = "adadbaa37ca743d5a6c3e3b2d311fb3c"

[[kv_namespaces]]
binding = "SESSION"
id = "adadbaa37ca743d5a6c3e3b2d311fb3c"
preview_id = "adadbaa37ca743d5a6c3e3b2d311fb3c"